export const state = {
  level: 1,
  score: 0,
  gridSize: 3,
  activeCount: 3,
  pattern: [] as number[],
  decoys: [] as number[],
  rhythmDelays: [] as number[],
  userClicks: [] as number[],
  isPlayable: false,
  isPaused: false,
  streak: 0,
  maxStreak: 0,
  mistakes: 0,
  clears: 0,
  earnedFragments: 0,
  combo: 0,
  maxCombo: 0,
  timerActive: false,
  totalTime: 0,
  timeLeft: 0,
  lastFrameTime: 0,
  timerAnimationId: 0,
  lastClickTime: 0,
  nBackStream: [] as number[],
  nBackStep: 0,
  nBackActive: false,
  nBackIsFlashing: false,
  levelTimeStart: 0,
  isDailyRun: false,
  wasTimerActiveBeforePause: false,
  curProtIdx: 0,
  curPaceIdx: 0,
  isOnboarding: false,
};
